import React, { useEffect, useMemo, useRef, useState } from "react";
import { prepareFuzzySearch, sortSearchResults } from "obsidian";
import type { SearchResult } from "obsidian";
import { useT } from "./TranslatorContext";
import { isComposing } from "./keyboard";

/** A `/name`-command entry surfaced for autocomplete. */
export interface CommandEntry {
	name: string;
	description: string;
	kind: "template" | "skill";
	/** Text inserted after `/`; differs only for a shadowed skill. */
	invocation: string;
}

interface CommandMenuProps {
	/** All available prompt templates and skills, in service-defined order. */
	commands: CommandEntry[];
	/** The text after the leading `/`, lowercased. Matching is case-insensitive regardless. */
	query: string;
	/**
	 * The listbox's id, generated by the composer — the same value its textarea
	 * names in `aria-controls`. The composer owns the id because the combobox
	 * wiring has to agree on it from both ends; the menu only wears it.
	 */
	menuId: string;
	/**
	 * Reports the highlighted option's id whenever it moves, and `null` when
	 * nothing is highlighted (no matches, or the menu going away). The composer
	 * mirrors that onto the textarea's `aria-activedescendant` — the one channel
	 * through which a screen reader hears the highlight — so the two attributes
	 * cannot drift apart. Option ids are derived from {@link CommandMenuProps.menuId},
	 * so the reported value is always one the composer can quote verbatim.
	 */
	onActiveChange?: (activeOptionId: string | null) => void;
	/**
	 * Called with the chosen entry. The composer inserts its invocation plus a
	 * trailing space so the user can keep typing arguments.
	 */
	onSelect: (command: CommandEntry) => void;
	/** Called when the user dismisses the menu (Escape or blur). */
	onClose: () => void;
}

/**
 * Autocomplete list for `/name` prompt templates and skills, floated above the composer.
 *
 * Keyboard-only by design: the composer opens it on `/`, and the arrow keys and
 * Enter it owns here are the ones that complete a command. Enter *completes*
 * rather than sends — a half-typed `/su` should not fire a prompt — so the
 * composer's send handler bails while this menu is open.
 *
 * The list fuzzy-matches Obsidian-style on the text after `/` — subsequence hits
 * like `/org` → `tag-organize` rank tighter matches first — rather than by
 * prefix, because hyphenated skill names would otherwise force users to recall
 * where a name starts instead of what it sounds like. With no matches it renders
 * nothing, which lets the composer treat `/unknown` as a normal (if invalid)
 * draft until the user sends it.
 *
 * It plays the option half of the ARIA combobox pattern: the composer's textarea
 * carries `role="combobox"` and quotes the highlighted option through
 * `aria-activedescendant`, which this menu keeps current via
 * {@link CommandMenuProps.onActiveChange}. The textarea is where focus lives —
 * the user is typing the command — so the ownership boundary is fixed by the
 * pattern, not by preference.
 */
export function CommandMenu({ commands, query, menuId, onActiveChange, onSelect, onClose }: CommandMenuProps): React.JSX.Element | null {
	const t = useT();
	const matches = useMemo(() => {
		if (!query) {
			// An empty query opens the full list in service order — no scoring needed.
			return commands;
		}
		const search = prepareFuzzySearch(query);
		const scored = commands
			.map((command) => ({ command, match: search(command.name) }))
			.filter((entry): entry is { command: CommandEntry; match: SearchResult } => entry.match !== null);
		sortSearchResults(scored);
		return scored.map((entry) => entry.command);
	}, [commands, query]);
	const [activeIndex, setActiveIndex] = useState(0);
	const listRef = useRef<HTMLUListElement | null>(null);
	/*
	 * The id of the highlighted option, in the combobox grammar. Guarded by the
	 * lookup rather than the index alone: for one render after the query narrows,
	 * `activeIndex` can still point past the (shorter) filtered set — the reset
	 * effect below has not run yet — and quoting a nonexistent id would leave
	 * `aria-activedescendant` dangling on exactly the frame a screen reader asks.
	 */
	const activeOptionId = matches[activeIndex] ? `${menuId}-option-${activeIndex}` : null;

	// Keep the highlight inside the filtered set as the query narrows.
	useEffect(() => {
		setActiveIndex(0);
	}, [matches.length]);

	// Mirror the highlight up to the composer's `aria-activedescendant`, and
	// clear it on the way out so the textarea never advertises a menu that left.
	const onActiveChangeRef = useRef(onActiveChange);
	onActiveChangeRef.current = onActiveChange;
	useEffect(() => {
		onActiveChangeRef.current?.(activeOptionId);
		return () => onActiveChangeRef.current?.(null);
	}, [activeOptionId]);

	// Scroll the highlighted row into view as the highlight moves.
	useEffect(() => {
		const list = listRef.current;
		if (!list) {
			return;
		}
		const item = list.children[activeIndex] as HTMLElement | undefined;
		item?.scrollIntoView({ block: "nearest" });
	}, [activeIndex]);

	/*
	 * The keydown handler reads live state through this ref, so the document
	 * listener can be bound once (on mount) and never churned on every keystroke.
	 * A re-binding effect would leave stale listeners on the document across test
	 * teardowns that do not unmount — and the ref is also the cheaper, correct
	 * shape: one listener, reading whatever the latest render wrote.
	 */
	const stateRef = useRef({ matches, activeIndex, onSelect, onClose });
	stateRef.current = { matches, activeIndex, onSelect, onClose };

	useEffect(() => {
		const handleKeyDown = (event: KeyboardEvent): void => {
			// An input method mid-composition owns the keyboard: Enter accepts the
			// candidate, Escape cancels it, and the arrows page the candidate list.
			// Completing a command on any of them hijacks the composition — the same
			// guard the send path applies, shared from `keyboard.ts`.
			if (isComposing(event)) {
				return;
			}
			const { matches: currentMatches, activeIndex: currentIndex, onSelect: currentOnSelect, onClose: currentOnClose } =
				stateRef.current;
			if (currentMatches.length === 0) {
				if (event.key === "Escape") {
					event.preventDefault();
					event.stopPropagation();
					currentOnClose();
				}
				return;
			}
			if (event.key === "ArrowDown") {
				event.preventDefault();
				event.stopPropagation();
				setActiveIndex((index) => (index + 1) % currentMatches.length);
				return;
			}
			if (event.key === "ArrowUp") {
				event.preventDefault();
				event.stopPropagation();
				setActiveIndex((index) => (index - 1 + currentMatches.length) % currentMatches.length);
				return;
			}
			// Plain Enter completes the highlighted command. A modifier chord
			// (⌘/Ctrl+Enter) is the send shortcut, and send is sacred: let it pass so
			// the composer's own listener can fire it. Completing on ⌘↵ would swallow
			// a send the user clearly asked for.
			if (event.key === "Enter" && !event.metaKey && !event.ctrlKey && !event.altKey) {
				event.preventDefault();
				event.stopPropagation();
				const match = currentMatches[currentIndex];
				if (match) {
					currentOnSelect(match);
				}
				return;
			}
			if (event.key === "Escape") {
				event.preventDefault();
				event.stopPropagation();
				currentOnClose();
			}
		};

		// Capture phase on document, ahead of the composer's own send handler, so
		// Enter here never reaches send. Bound once for the menu's lifetime.
		document.addEventListener("keydown", handleKeyDown, { capture: true });
		return () => {
			document.removeEventListener("keydown", handleKeyDown, { capture: true });
		};
	}, []);

	if (matches.length === 0) {
		return null;
	}

	return (
		<ul ref={listRef} id={menuId} className="piem-chat__command-menu" role="listbox" aria-label={t.t("chat.commandMenuAria")}>
			{matches.map((match, index) => (
				<li
					key={`${match.kind}:${match.name}`}
					id={`${menuId}-option-${index}`}
					role="option"
					aria-selected={index === activeIndex}
					className="piem-chat__command-menu-item"
				>
					<button
						type="button"
						className="piem-chat__command-menu-button"
						onMouseEnter={() => setActiveIndex(index)}
						onClick={() => onSelect(match)}
						tabIndex={-1}
					>
						<span className="piem-chat__command-menu-heading">
							<span className="piem-chat__command-menu-name">/{match.name}</span>
							<span className="piem-chat__command-menu-kind">
								{t.t(match.kind === "template" ? "chat.commandKindTemplate" : "chat.commandKindSkill")}
							</span>
						</span>
						{match.description ? <span className="piem-chat__command-menu-desc">{match.description}</span> : null}
					</button>
				</li>
			))}
		</ul>
	);
}
